version: '3.8'

services:
  web:
    build: .
    container_name: python_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Map the current directory to /app in the container
      - /app/__pycache__  # Ignore Python cache files
    depends_on:
      - memcached
    environment:
      # Make sure these values match the ones in your Dockerfile (if used)
      MEMCACHED_HOST: memcached
      MEMCACHED_PORT: 11211

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    command: memcached -m 64
